export const sections = [
  {
    id: "s1",
    images: [
      {
        id: "wenkCV",
        title: "POI exterior shot",
        src: "https://live.staticflickr.com/65535/51968060505_4ffd33405d_o.jpg",
        alt: "Portraits of Iowa exterior shot",
        caption: "Portraits of Iowa at night",
        hideImage: false,
      },
      {
        id: "yO8FSP",
        title: "POI Sketchup",
        src: "https://live.staticflickr.com/65535/51968060520_974ca515af_o.jpg",
        alt: "Portraits of Iowa Sketchup graphic",
        caption: "Photos suspended inside the Lantern",
        hideImage: false,
      },
    ],
  },
  {
    id: "s2",
    images: [
      {
        id: "c1ld6G",
        title: "POI lighting",
        src: "https://live.staticflickr.com/65535/51976109719_20bbaee7f0_o.jpg",
        alt: "Hanging portraits, lighting concept.",
        caption: "",
        hideImage: false,
      },
      {
        id: "fxImvV",
        title: "POI abstract",
        src: "https://live.staticflickr.com/65535/51966496477_afb09a46ba_o.jpg",
        alt: "Hanging portraits, abstract.",
        caption: "",
        hideImage: true,
      },
      {
        id: "aMPWYv",
        title: "POI multitudes",
        src: "https://live.staticflickr.com/65535/51967563498_14275145f6_o.jpg",
        alt: "Hanging portraits, multitudes.",
        caption: "",
        hideImage: false,
      },
      {
        id: "B9x6fX",
        title: "POI closeup",
        src: "https://live.staticflickr.com/65535/51967782849_3f576e3b9d_o.jpg",
        alt: "Hanging portraits, closeup.",
        caption: "",
        hideImage: false,
      },
    ],
  },
  {
    id: "s3",
    images: [
      {
        id: "iQYiyB",
        title: "POI concept with figure.",
        src: "https://live.staticflickr.com/65535/51976382805_493884f704_o.jpg",
        alt: "POI concept with figure.",
        caption: "",
        hideImage: false,
      },
      {
        id: "wf4c43",
        title: "s3-a",
        src: "https://live.staticflickr.com/65535/51968060915_124106f66d_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "vJjxpI",
        title: "s3-b",
        src: "https://live.staticflickr.com/65535/51967500756_74e77f1aed_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "knEjsp",
        title: "s3-c",
        src: "https://live.staticflickr.com/65535/51967500771_06dcd800e0_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "b1cXpv",
        title: "s3-d",
        src: "https://live.staticflickr.com/65535/51967783124_eefee42db8_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: true,
      },
      {
        id: "r1T1Bx",
        title: "s3-e",
        src: "https://live.staticflickr.com/65535/51967500701_c0d204542d_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: true,
      },
      {
        id: "04erMg",
        title: "s3-f",
        src: "https://live.staticflickr.com/65535/51967564158_3fab579ef4_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "AYkWM7",
        title: "s3-g",
        src: "https://live.staticflickr.com/65535/51966496992_c3ef6422e7_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "YzGn2t",
        title: "s3-h",
        src: "https://live.staticflickr.com/65535/51966496972_ccb8f3e909_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "qgY78H",
        title: "s3-i",
        src: "https://live.staticflickr.com/65535/51966496932_a676701c16_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "51nNBD",
        title: "s3-j",
        src: "https://live.staticflickr.com/65535/51968061040_d99bd13087_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: true,
      },
      {
        id: "jOadBd",
        title: "s3-k",
        src: "https://live.staticflickr.com/65535/51967564138_9534cc4144_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "wWmUSn",
        title: "s3-l",
        src: "https://live.staticflickr.com/65535/51968061225_27b0ca4011_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "cZfMix",
        title: "s3-m",
        src: "https://live.staticflickr.com/65535/51967501016_e1d0bd71bd_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: false,
      },
      {
        id: "iJkAq2",
        title: "s3-n",
        src: "https://live.staticflickr.com/65535/51966497022_58a863292f_o.jpg",
        alt: "POI section 3 gallery item",
        caption: "",
        hideImage: true,
      },
    ],
  },
  {
    id: "s4",
    rows: [
      {
        id: "r1",
        pairs: [
          {
            id: "1a",
            hidePair: false,
            images: [
              {
                id: "9sH5dC",
                title: "1a-original",
                src: "https://live.staticflickr.com/65535/51972168819_c7f126beba_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
              {
                id: "pinscE",
                title: "1a-edited",
                src: "https://live.staticflickr.com/65535/51972442215_8d6fc6ec07_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
            ],
          },
          {
            id: "1b",
            hidePair: false,
            images: [
              {
                id: "tVFJe5",
                title: "1b-original",
                src: "https://live.staticflickr.com/65535/51971879596_1e9bd33f63_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
              {
                id: "m5OyDf",
                title: "1b-edited",
                src: "https://live.staticflickr.com/65535/51972168789_f6237566aa_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
            ],
          },
          {
            id: "1c",
            hidePair: true,
            images: [
              {
                id: "LDERVF",
                title: "1c",
                src: "https://live.staticflickr.com/65535/51970877987_d5998e24a8_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
              {
                id: "2ampym",
                title: "1c-edited",
                src: "https://live.staticflickr.com/65535/51972442170_c557df1fc6_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
            ],
          },
        ],
      },
      {
        id: "r2",
        hidePair: false,
        pairs: [
          {
            id: "2a",
            images: [
              {
                id: "hbB3Rg",
                title: "2a-original",
                src: "https://live.staticflickr.com/65535/51971879526_64217cc0a2_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
              {
                id: "uDkylp",
                title: "2a-edited",
                src: "https://live.staticflickr.com/65535/51971949383_3d5f39da99_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
            ],
          },
          {
            id: "2b",
            hidePair: false,
            images: [
              {
                id: "6NXD26",
                title: "2b-original",
                src: "https://live.staticflickr.com/65535/51972442330_ab28492bce_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
              {
                id: "Ofyvze",
                title: "2b-edited",
                src: "https://live.staticflickr.com/65535/51971879661_9258308367_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
            ],
          },
        ],
      },
      {
        id: "r3",
        hidePair: false,
        pairs: [
          {
            id: "3a",
            images: [
              {
                id: "FnYKoF",
                title: "3a-original",
                src: "https://live.staticflickr.com/65535/51971879656_cefe6a3a75_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
              {
                id: "JoLtz8",
                title: "3a-edited",
                src: "https://live.staticflickr.com/65535/51972168889_845c8af098_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
            ],
          },
          {
            id: "3b",
            hidePair: false,
            images: [
              {
                id: "uhXukI",
                title: "3b-original",
                src: "https://live.staticflickr.com/65535/51971879636_6922559ca7_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
              {
                id: "Uxklb5",
                title: "3b-edited",
                src: "https://live.staticflickr.com/65535/51972442235_9ec93c07a1_o.jpg",
                alt: "POI section 4 gallery item",
                caption: "",
                hideImage: false,
              },
            ],
          },
        ],
      },
    ],
  },
];
